name: Deploy MkDocs to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install mkdocs-material mkdocs-material-extensions mkdocstrings[python]
                  pip install -e .

            - name: Build and Deploy
              working-directory: docs # Set the working directory to 'docs'
              env:
                  PYTHONPATH: ${{ github.workspace }} # Set PYTHONPATH to the root directory
              run: |
                  mkdocs gh-deploy --force
